language: node_js
node_js:
  - "0.10"

before_install: 
  - sudo apt-get install sqlite3
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g mocha
  - npm install -g should

install: npm install
before_script: grunt dev
script: npm test
